# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_boards', '0005_topic_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='last_uptated',
            new_name='last_updated',
        ),
    ]
